version: "3.9"
services:
  api:
    container_name: api
    build: ./api
    ports:
      - 8080:8080
    tty: true
    volumes:
      # この中では相対パスを使用できる。cachedは同期性は少し犠牲になるが、応答スピードが上がる
      - ./api:/workspace:cached
  web:
    container_name: web
    build:
      context: ./web
      target: base
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_SERVER=http://localhost:8080/api
    tty: true
    volumes:
      # workspaceの名前同じだが関係ない
      - ./web:/workspace:cached
    depends_on:
      - api
